In [1]:
import torch
import torchvision

In [50]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.randn(3, 4, 5).type(torch.float32)

In [51]:
# Выведите его форму (shape)
print(x.shape)

torch.Size([3, 4, 5])


In [52]:
# Приведите его к форме 6 X 10
x_reshaped = x.reshape(6, 10)
x_reshaped.shape

torch.Size([6, 10])

In [55]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x * torch.LongTensor([1, 4, 2, 2, 1])

tensor([[[-0.7499, -0.2737, -0.8507,  2.2938, -0.5073],
         [ 2.1882, -0.0937, -4.0180,  1.8087, -0.0263],
         [-0.1879,  0.1444,  1.3021, -1.9485,  0.0748],
         [-0.8489, -5.9156,  1.7853, -1.7034,  1.2753]],

        [[-0.2601, -7.9931, -1.1137,  3.3888,  0.4065],
         [ 0.8212,  1.7458,  4.6509, -3.3481,  0.1471],
         [ 0.3116,  0.3622,  1.3441, -2.8856,  0.0412],
         [-1.3735, -4.8372,  0.2355,  1.7282, -0.5221]],

        [[ 2.6296, -1.1750, -0.9789,  0.8198,  0.1480],
         [-1.3734,  3.7610, -2.5706, -3.0441, -0.7952],
         [-0.5282, -4.1566, -2.4153, -3.1092, -0.7831],
         [-0.2348,  4.8794, -1.1747, -4.5002, -0.8466]]])

In [57]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
y = torch.matmul(x_reshaped, torch.transpose(x_reshaped, 0, 1))
y.shape

torch.Size([6, 6])

In [61]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)


from torch.autograd import Variable


x = Variable(torch.FloatTensor([1.]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2.]), requires_grad = True)


y = x**3 + z - 75 * t
y

tensor([-148.5000], grad_fn=<SubBackward0>)

In [62]:
y.backward([x, z, t])
print(torch.stack([x.grad, z.grad, t.grad]).sum())

tensor(-71.)


In [63]:
# Создайте единичный тензор размера 5x6
z = torch.ones(5, 6)
z

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [49]:
# Переведите его в формат numpy
z.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [80]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

from torch import nn, optim


w1 = Variable(torch.randn(1), requires_grad = True)
x = Variable(torch.randn(1), requires_grad = True)
y = Variable(torch.randn(1), requires_grad = False)

optimizer = optim.Adam([w1], lr=0.01)
criterion = nn.MSELoss()

w1, x, y

(tensor([1.0450], requires_grad=True),
 tensor([0.9240], requires_grad=True),
 tensor([-0.3700]))

In [82]:
optimizer.zero_grad()

pred = (x**w1) - (2 * x**2) + 5
loss = criterion(pred, y)

print('loss: ', loss.item())

loss:  21.006338119506836


In [83]:
loss.backward()
optimizer.step()
w1

tensor([1.0550], requires_grad=True)